Install V2 Core and V2 Periphery
sablier-labs/examples pull request #11
Opened 2023-07-08 15:33 UTC by andreivladbrg

Closes https://github.com/sablier-labs/examples/issues/9

2023-07-09 10:04 UTC, PaulRBerg commented on cache/solidity-files-cache.json
cache files should not be committed

2023-07-09 10:09 UTC, PaulRBerg commented on src/v2/periphery/BatchLockupDynamicStreamCreator.sol
> +        stream0.totalAmount = uint128(transferAmount); // The total amount of each stream, inclusive of all fees
Should be `perStreamAmount`.

2023-07-09 10:10 UTC, PaulRBerg commented on src/v2/periphery/BatchLockupDynamicStreamCreator.sol
> +        stream1.totalAmount = uint128(transferAmount); // The total amount of each stream, inclusive of all fees
Should be `perStreamAmount`

2023-07-09 10:10 UTC, PaulRBerg commented on src/v2/periphery/BatchLockupLinearStreamCreator.sol
> +        stream0.totalAmount = uint128(transferAmount); // The total amount of each stream, inclusive of all fees
Should be `perStreamAmount`.

2023-07-09 10:10 UTC, PaulRBerg commented on src/v2/periphery/BatchLockupLinearStreamCreator.sol
> +        stream1.totalAmount = uint128(transferAmount); // The total amount of each stream, inclusive of all fees
Should be `perStreamAmount`.

2023-07-09 10:14 UTC, PaulRBerg requested changes
There's no need to add a new `src` directory - we can just point `src` to `v2` in `foundry.toml`. I'll push a commit to do this.

2023-07-09 10:26 UTC, andreivladbrg commented on cache/solidity-files-cache.json
Yeah, this is why I added the `.gitignore` file
https://github.com/sablier-labs/examples/blob/a261314f05e5cd6b0b67642eacf6ec1f3dfa1b32/.gitignore#L2

Might have pushed it by mistake

2023-07-09 10:49 UTC, PaulRBerg approved these changes
LGTM now

2023-07-09 10:50 UTC, merged

2023-07-09 11:07 UTC, PaulRBerg commented
Thanks for merging @andreivladbrg - in the future, can we squash & merge when there are commits of the sort "fix: address PR feedback"?

2023-07-09 20:34 UTC, andreivladbrg commented
>  can we squash & merge when there are commits

I actually used squash & merge, see [here](https://github.com/sablier-labs/examples/commit/eae781627e15d963a62c1545fe0944ad94d5519c).

>   "fix: address PR feedback"

Do you mean to actually remove the message?

2023-07-10 07:01 UTC, PaulRBerg commented
> I actually used squash & merge, see [here](https://github.com/sablier-labs/examples/commit/eae781627e15d963a62c1545fe0944ad94d5519c).

Oh, sorry! Good job

> Do you mean to actually remove the message?

No